In [3]:
import numpy as np

In [4]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [5]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [6]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [7]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[66 56 93 94 52 59]


In [8]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[50 54 85 90 87 93]


In [9]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[50 67 64 79 71 90]


In [10]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.43991207 0.92564469 0.5219449  0.19987667 0.14198222 0.89457092]


In [11]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.43991207 2.92564469 2.5219449  2.19987667 2.14198222 2.89457092]


In [12]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[150 201 192 237 213 270]


In [15]:
feature = np.arange(6, 21)

In [16]:
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [17]:
label = (feature * 3) + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [18]:
noise = np.random.random([4])

In [19]:
print(noise)

[0.01761938 0.10013522 0.19418352 0.57270011]


In [21]:
noise = np.random.random([7]) + 1

In [22]:
noise = noise + 1

In [23]:
print(noise)

[2.72291795 2.87842488 2.87366205 2.33383672 2.12210267 2.88562195
 2.92903013]


In [24]:
noise = np.random.random([7]) + 1

In [26]:
print(noise)

[[[[-1.38559101 -1.1918733  -1.99415847 ... -1.90227867 -1.55715602
    -1.45036224]
   [-1.11739781 -1.51131189 -1.39368924 ... -1.96206763 -1.66573382
    -1.47119767]
   [-1.329788   -1.59148996 -1.69120001 ... -1.63283949 -1.88747857
    -1.02898763]
   ...
   [-1.01436244 -1.14935903 -1.86498661 ... -1.43829707 -1.08023287
    -1.37327914]
   [-1.7470325  -1.79558514 -1.40962209 ... -1.21581446 -1.54350873
    -1.90413998]
   [-1.97949245 -1.54056617 -1.53656427 ... -1.01809    -1.696807
    -1.87458467]]

  [[-1.53246572 -1.67101735 -1.73113245 ... -1.1354579  -1.50447691
    -1.31776299]
   [-1.34570676 -1.59244074 -1.07756121 ... -1.44340435 -1.38379531
    -1.56147285]
   [-1.69540078 -1.66876016 -1.25000514 ... -1.79417027 -1.45889992
    -1.9269649 ]
   ...
   [-1.07018867 -1.07148614 -1.35977549 ... -1.53777167 -1.13941869
    -1.14539142]
   [-1.95304867 -1.60495694 -1.76239    ... -1.33358462 -1.05146703
    -1.27013297]
   [-1.07683332 -1.898247   -1.00096197 ... -1.4796

In [34]:
noise = (np.random.random([15]) * 4) -2
print(noise)
label = label + noise
print(label)

[-1.43420881 -1.94052837  1.4324027  -1.05473193 -0.48542974  1.15873224
  0.05849216  0.70920804  0.88673051  1.04716009  0.55105371  1.9930772
  1.09166195  1.48884267  1.24782421]
[20.56579119 23.05947163 29.4324027  29.94526807 33.51457026 38.15873224
 40.05849216 43.70920804 46.88673051 50.04716009 52.55105371 56.9930772
 59.09166195 62.48884267 65.24782421]
